hydra:
  output_subdir: null
  run:
    dir: "."

defaults:
  - hydra/job_logging: disabled

env_name: "Hopper-v3"
num_trajs: 4
seed: 0
ensemble_shuffle_type: "sample_w_replace"
device: "cuda"
uncertainty_reward: "ensemble"
ensemble_hidden_size: 512
ensemble_drop_rate: 0.1
ensemble_size: 5
ensemble_batch_size: 100
ensemble_lr: 2.5e-4
num_ensemble_train_epoch: 1000
training_data_split: 0.9
save_model_dir: "../saves"
save_results_dir: "../saves"
ensemble_quantile_threshold: 0.98
dril_cost_clip : "-1_to_1"
dril_uncertainty_reward: "ensemble"