hydra:
  output_subdir: null
  run:
    dir: "."

defaults:
  - hydra/job_logging: disabled

env_id: "Hopper-v3"
n_envs: 5
n_evals: 50

trial: 1
save_dir: "saves"
save_name: "sac_Hopper-v3_1.zip"
demo_name: "sac_Hopper_demo"

n_trajs: 4
traj_length: 1000


#lr: 3e-4
#batch_size: 128
#weight_decay: 0
#epochs: 200

#BC parameters
lr: 3e-4
batch_size: 128
weight_decay: 0
epochs: 50

#RL parameters
policy_kwargs: "dict(net_arch=[400, 300])"

train_steps: 5e6

rl_batch_size: 256
learning_rate: 0.0004
#  0.0004

gradient_steps: 5
train_freq: 5

buffer_size: 300000
learning_start: 10000

gamma: 0.99
tau: 0.01

eval_freq: 5000